name: Build and Push Docker Image

permissions:
  contents: write

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: microlearn
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Generate release tag
        id: tag
        run: |
          TODAY=$(date +'%Y.%m.%d')
          EXISTING_TAGS=$(git tag -l "v-${TODAY}.*" | wc -l)
          SEQUENCE=$((EXISTING_TAGS + 1))
          echo "release_tag=v-${TODAY}.${SEQUENCE}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/mlcg:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/mlcg:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/mlcg:${{ steps.tag.outputs.release_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          generate_release_notes: true
